### ISSUE TITLE
Can't import object from package

### ISSUE THREAD

**Issue by nechmads** [RobertSheaO/react-native-zendesk-support#21]
I linked the library and configured the iOS SDK like in the documentation.
Build goes well but when running the app it seems I can't import ZendeskSupport.

import ZendeskSupport from 'react-native-zendesk-support';
ZendeskSupport seems to be an empty object and ZendeskSupport.initialize(config) throws an error:

_reactNativeZendeskSupport2.deafult.initialize is not a function.

**Comment by RobertSheaO** [comment]
Please reply with the version of React Native you're using, and confirm the following:

- Confirm that `libRNZenDeskSupport.a` is listed in Xcode under YourProject > Targets > YourProject > Build Phases > Link Binary With Libraries.
- Confirm that `RNZenDeskSupport.xcodeproj` appears under the `Libraries` folder in the left pane of Xcode

If one or both of these things are not setup, then linking failed, and you can follow the `Manually Linking (iOS)` step in the README

**Comment by nechmads** [comment]
Thanks for answering. I tried to manually link it but then I get "ld: framework not found ZendeskProviderSDK" error when trying to build from Xcode.

Do you happen to have an example project working I can look at as reference? Couldn't find any out there.

**Comment by nechmads** [comment]
By the way, when I use "react-native link" everything seems to work fine but in reality I don't see it doing anything.
On console I see messages:
rnpm-install info Linking react-native-zendesk-support ios dependency 
rnpm-install info iOS module react-native-zendesk-support has been successfully linked 

But opening the workspace in Xcode, I can't see react-native-zendesk-support libraries in the link phase or the project added anywhere

**Comment by RobertSheaO** [comment]
I’ll put one up this evening and add it to the repository under an examples
directory

**Comment by nechmads** [comment]
Thanks! Appreciate the help!!

**Comment by RobertSheaO** [comment]
Oh, by the way, it is 3:23 PM where I am so I’ll put it up in about 10
hours when I’m done skiing.

**Comment by nechmads** [comment]
Ha ha. Enjoy the slopes!!

Actually, managed get things working. I wish I could tell you how. I basically just added, removed and re-added libraries and suddenly the link worked!

**Comment by RobertSheaO** [comment]
Had you tried the following? I imagine add/remove/add triggered this...

- In Xcode `Product > Clean`,
- in Xcode `Product > Clean Build Folder` (hold option key)
- In terminal in your project dir `rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean --force`

P.S. I still plan to put an example up; however, I'll create a Medium.com article about it, rather than put in the repo. I don't wanna have to deal with code splitting between GitHub and the NPM repository

**Comment by RobertSheaO** [comment]
Also, I have the following scripts in my `package.json` file that could be of help if you don't have them already. Whenever I run into a problem like this, I always run them. They came out of the box with my Ignite generated base app, though I've modified them slightly to use `yarn` instead of `npm`. The `npm run newclear` nukes your `node_modules` directory, so if you've made local changes inside there, be aware.

```json
"scripts": {
  "clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean --force",
  "newclear": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && npm cache clean --force && yarn install"
}
```
