### ISSUE TITLE
Viewing Help Center Requires User Login

### ISSUE THREAD

**Issue by jaga-me** [RobertSheaO/react-native-zendesk-support#5]
It seems like in order for the user to view the help center, the user has to be logged in. 

Is that correct and can there be a way we identify the user without filing a support ticket?

**Comment by RobertSheaO** [comment]
The ability to authenticate via JWT is on the TODO list. As for authenticating anonymously to view a locked control center, I'll look into that. I'm not specifically authenticating and it works on my end, but I'll run some tests.

**Comment by RobertSheaO** [comment]
I'm able to reproduce the error your encountered by calling `ZenDeskSupport.showHelpCenter()` first. If I call `ZenDeskSupport.callSupport()` or `ZenDeskSupport. supportHistory()` first, then the issue doesn't present it's self. I'll release a build soon that allows you to define an identity in order to see a locked control center.

**Comment by RobertSheaO** [comment]
This is now fixed as a patch 0.3.3, and in 1.0.0
