### ISSUE TITLE
run-android Could not find com.zendesk:sdk:1.10.1.1. 

### ISSUE THREAD

**Issue by HyuArzani** [RobertSheaO/react-native-zendesk-support#6]
hello, 
get this error when run-android
![image](https://user-images.githubusercontent.com/27977978/30575993-d9782772-9d2e-11e7-81a0-f644674964c0.png)

the build.gradle repo already:

repositories {
	mavenCentral()
    maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
}

dependencies {
    compile 'com.facebook.react:react-native:+'
    compile group: 'com.zendesk', name: 'sdk', version: '1.10.1.1'
}

**Comment by RobertSheaO** [comment]
When following [these instructions](https://developer.zendesk.com/embeddables/docs/android/integrate_sdk#adding-the-support-sdk-with-gradle), make sure to put that info into your `android/app/build.gradle` and not your `android/build.gradle` file.

For reference, this is what my `android/app/build.gradle` looks like:

```
repositories {
    maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
}

dependencies {
    compile project(':react-native-zendesk-support')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile group: 'com.zendesk', name: 'sdk', version: '1.10.1.1'
}
```

Since you're missing `compile project(':react-native-zendesk-support')` in the snippet you provided, you may have forgotten to run `react-native link react-native-zendesk-support`

**Comment by HyuArzani** [comment]
yes, the problem was need to add :
repositories {
    maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
},
in app/build.gradle, i miss this one
also this lib doesn't compatible with react<0.40
thanks,

**Comment by RobertSheaO** [comment]
Okay, thanks for the heads up about <0.40 support. I’ve only tested this with 0.47

**Comment by RobertSheaO** [comment]
@HyuArzani Could you update your package.json to the following to test if my latest change makes it work for RN < 0.40?

```
"react-native-zendesk-support": "git+https://github.com/RobertSheaO/react-native-zendesk-support",
```

**Comment by RobertSheaO** [comment]
@HyuArzani With version 1.0.1, you no longer have to integrate the Zendesk Support SDK into your android and iOS projects. You can initialize it through this module. You'll need to keep the following in your `android/app/build.gradle` file though

```
repositories {
    maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
}
```
